<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>ArmelloUrlFix</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <RestorePackages>false</RestorePackages>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>D:\Program Files (x86)\SteamLibrary\steamapps\common\Armello\BepInEx\core\BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>D:\Program Files (x86)\SteamLibrary\steamapps\common\Armello\BepInEx\core\BepInEx.Unity.IL2CPP.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>D:\Program Files (x86)\SteamLibrary\steamapps\common\Armello\BepInEx\core\0Harmony.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>D:\Program Files (x86)\SteamLibrary\steamapps\common\Armello\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>D:\Program Files (x86)\SteamLibrary\steamapps\common\Armello\BepInEx\interop\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>D:\Program Files (x86)\SteamLibrary\steamapps\common\Armello\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>D:\Program Files (x86)\SteamLibrary\steamapps\common\Armello\BepInEx\unity-libs\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
